server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: Sriram@1310

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

services:
  order:
    base-url: http://localhost:8083

app:
  service-name: Payment Service
  message: Payment configuration loaded from GitHub

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
